sudo: required
services:
  - docker

env:
  - CC="clang" CFLAGS="-O2 -g -Wall -Wextra -Werror -Wno-incompatible-library-redeclaration -Wno-deprecated-declarations" OS="Gentoo" BUILD_FLAGS="--with-gtk3 --with-libnotify"
  - CC="clang" CFLAGS="-O2 -g -Wall -Wextra -Werror -Wno-incompatible-library-redeclaration -Wno-deprecated-declarations" OS="Gentoo" BUILD_FLAGS="--with-gtk3 --without-libnotify"
  - CC="clang" CFLAGS="-O2 -g -Wall -Wextra -Werror -Wno-incompatible-library-redeclaration -Wno-deprecated-declarations" OS="Gentoo" BUILD_FLAGS="--without-gtk3 --with-libnotify"
  - CC="clang" CFLAGS="-O2 -g -Wall -Wextra -Werror -Wno-incompatible-library-redeclaration -Wno-deprecated-declarations" OS="Gentoo" BUILD_FLAGS="--without-gtk3 --without-libnotify"
  - CC="gcc" CFLAGS="-O2 -g -Wall -Wextra -Werror -fno-builtin -Wno-deprecated-declarations" OS="Gentoo" BUILD_FLAGS="--with-gtk3 --with-libnotify"
  - CC="gcc" CFLAGS="-O2 -g -Wall -Wextra -Werror -fno-builtin -Wno-deprecated-declarations" OS="Gentoo" BUILD_FLAGS="--with-gtk3 --without-libnotify"
  - CC="gcc" CFLAGS="-O2 -g -Wall -Wextra -Werror -fno-builtin -Wno-deprecated-declarations" OS="Gentoo" BUILD_FLAGS="--without-gtk3 --with-libnotify"
  - CC="gcc" CFLAGS="-O2 -g -Wall -Wextra -Werror -fno-builtin -Wno-deprecated-declarations" OS="Gentoo" BUILD_FLAGS="--without-gtk3 --without-libnotify"
  - CC="clang" CFLAGS="-O2 -g -Wall -Wextra -Werror -Wno-incompatible-library-redeclaration -Wno-deprecated-declarations" OS="Debian" BUILD_FLAGS="--with-gtk3 --with-libnotify"
  - CC="clang" CFLAGS="-O2 -g -Wall -Wextra -Werror -Wno-incompatible-library-redeclaration -Wno-deprecated-declarations" OS="Debian" BUILD_FLAGS="--with-gtk3 --without-libnotify"
  - CC="clang" CFLAGS="-O2 -g -Wall -Wextra -Werror -Wno-incompatible-library-redeclaration -Wno-deprecated-declarations" OS="Debian" BUILD_FLAGS="--without-gtk3 --with-libnotify"
  - CC="clang" CFLAGS="-O2 -g -Wall -Wextra -Werror -Wno-incompatible-library-redeclaration -Wno-deprecated-declarations" OS="Debian" BUILD_FLAGS="--without-gtk3 --without-libnotify"
  - CC="gcc" CFLAGS="-O2 -g -Wall -Wextra -Werror -fno-builtin -Wno-deprecated-declarations" OS="Debian" BUILD_FLAGS="--with-gtk3 --with-libnotify"
  - CC="gcc" CFLAGS="-O2 -g -Wall -Wextra -Werror -fno-builtin -Wno-deprecated-declarations" OS="Debian" BUILD_FLAGS="--with-gtk3 --without-libnotify"
  - CC="gcc" CFLAGS="-O2 -g -Wall -Wextra -Werror -fno-builtin -Wno-deprecated-declarations" OS="Debian" BUILD_FLAGS="--without-gtk3 --with-libnotify"
  - CC="gcc" CFLAGS="-O2 -g -Wall -Wextra -Werror -fno-builtin -Wno-deprecated-declarations" OS="Debian" BUILD_FLAGS="--without-gtk3 --without-libnotify"
  - CC="clang" CFLAGS="-O2 -g -Wall -Wextra -Werror -Wno-incompatible-library-redeclaration -Wno-deprecated-declarations" OS="Ubuntu" BUILD_FLAGS="--with-gtk3 --with-libnotify"
  - CC="clang" CFLAGS="-O2 -g -Wall -Wextra -Werror -Wno-incompatible-library-redeclaration -Wno-deprecated-declarations" OS="Ubuntu" BUILD_FLAGS="--with-gtk3 --without-libnotify"
  - CC="clang" CFLAGS="-O2 -g -Wall -Wextra -Werror -Wno-incompatible-library-redeclaration -Wno-deprecated-declarations" OS="Ubuntu" BUILD_FLAGS="--without-gtk3 --with-libnotify"
  - CC="clang" CFLAGS="-O2 -g -Wall -Wextra -Werror -Wno-incompatible-library-redeclaration -Wno-deprecated-declarations" OS="Ubuntu" BUILD_FLAGS="--without-gtk3 --without-libnotify"
  - CC="gcc" CFLAGS="-O2 -g -Wall -Wextra -Werror -fno-builtin -Wno-deprecated-declarations" OS="Ubuntu" BUILD_FLAGS="--with-gtk3 --with-libnotify"
  - CC="gcc" CFLAGS="-O2 -g -Wall -Wextra -Werror -fno-builtin -Wno-deprecated-declarations" OS="Ubuntu" BUILD_FLAGS="--with-gtk3 --without-libnotify"
  - CC="gcc" CFLAGS="-O2 -g -Wall -Wextra -Werror -fno-builtin -Wno-deprecated-declarations" OS="Ubuntu" BUILD_FLAGS="--without-gtk3 --with-libnotify"
  - CC="gcc" CFLAGS="-O2 -g -Wall -Wextra -Werror -fno-builtin -Wno-deprecated-declarations" OS="Ubuntu" BUILD_FLAGS="--without-gtk3 --without-libnotify"

before_install: ./.travis/before_install.sh

install: ./.travis/install.sh

script: ./.travis/script.sh
